 export const PRIMARY_LOCATION = 'PRIMARY';
 export const SECONDARY_LOCATION = 'SECONDARY';
 export const THIRD_LOCATION = 'THIRD';
 export const NAVIGATION_LOCATION = 'NAVIGATION';
 export const FOOTER_LOCATION = 'FOOTER';
